-- AlterTable
ALTER TABLE "INSCRIPCIONES" ADD COLUMN     "COMPROBANTE_FILENAME" VARCHAR(255),
ADD COLUMN     "COMPROBANTE_PAGO_PDF" BYTEA,
ADD COLUMN     "COMPROBANTE_SIZE" INTEGER,
ADD COLUMN     "FEC_SUBIDA_COMPROBANTE" TIMESTAMP;

-- AlterTable
ALTER TABLE "INSCRIPCIONES_CURSO" ADD COLUMN     "COMPROBANTE_FILENAME" VARCHAR(255),
ADD COLUMN     "COMPROBANTE_PAGO_PDF" BYTEA,
ADD COLUMN     "COMPROBANTE_SIZE" INTEGER,
ADD COLUMN     "FEC_SUBIDA_COMPROBANTE" TIMESTAMP;
