"use strict";
// Exportar middlewares principales
Object.defineProperty(exports, "__esModule", { value: true });
exports.healthCheck = exports.notFoundHandler = exports.globalErrorHandler = exports.requestLogger = exports.validateIdParam = exports.validatePagination = exports.validateEventCreation = exports.validateCourseCreation = exports.validateChangePassword = exports.validateLogin = exports.validateUserUpdate = exports.validateUserCreation = exports.handleValidationErrors = exports.authorizeOwnerOrAdmin = exports.optionalAuth = exports.authorize = exports.authenticateToken = void 0;
var authMiddleware_1 = require("./authMiddleware");
Object.defineProperty(exports, "authenticateToken", { enumerable: true, get: function () { return authMiddleware_1.authenticateToken; } });
Object.defineProperty(exports, "authorize", { enumerable: true, get: function () { return authMiddleware_1.authorize; } });
Object.defineProperty(exports, "optionalAuth", { enumerable: true, get: function () { return authMiddleware_1.optionalAuth; } });
Object.defineProperty(exports, "authorizeOwnerOrAdmin", { enumerable: true, get: function () { return authMiddleware_1.authorizeOwnerOrAdmin; } });
var validationMiddleware_1 = require("./validationMiddleware");
Object.defineProperty(exports, "handleValidationErrors", { enumerable: true, get: function () { return validationMiddleware_1.handleValidationErrors; } });
Object.defineProperty(exports, "validateUserCreation", { enumerable: true, get: function () { return validationMiddleware_1.validateUserCreation; } });
Object.defineProperty(exports, "validateUserUpdate", { enumerable: true, get: function () { return validationMiddleware_1.validateUserUpdate; } });
Object.defineProperty(exports, "validateLogin", { enumerable: true, get: function () { return validationMiddleware_1.validateLogin; } });
Object.defineProperty(exports, "validateChangePassword", { enumerable: true, get: function () { return validationMiddleware_1.validateChangePassword; } });
Object.defineProperty(exports, "validateCourseCreation", { enumerable: true, get: function () { return validationMiddleware_1.validateCourseCreation; } });
Object.defineProperty(exports, "validateEventCreation", { enumerable: true, get: function () { return validationMiddleware_1.validateEventCreation; } });
Object.defineProperty(exports, "validatePagination", { enumerable: true, get: function () { return validationMiddleware_1.validatePagination; } });
Object.defineProperty(exports, "validateIdParam", { enumerable: true, get: function () { return validationMiddleware_1.validateIdParam; } });
var securityMiddleware_1 = require("./securityMiddleware");
Object.defineProperty(exports, "requestLogger", { enumerable: true, get: function () { return securityMiddleware_1.requestLogger; } });
Object.defineProperty(exports, "globalErrorHandler", { enumerable: true, get: function () { return securityMiddleware_1.globalErrorHandler; } });
Object.defineProperty(exports, "notFoundHandler", { enumerable: true, get: function () { return securityMiddleware_1.notFoundHandler; } });
Object.defineProperty(exports, "healthCheck", { enumerable: true, get: function () { return securityMiddleware_1.healthCheck; } });
