/*
  Warnings:

  - The values [PENDIENTE,EN_REVISION,APROBADA,RECHAZADA,PLANES_PENDIENTES_APROBACION,LISTO_PARA_IMPLEMENTAR,ESPERANDO_APROBACION,EN_TESTING,EN_DESPLIEGUE,FALLIDA] on the enum `EstadoSolicitud` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "EstadoSolicitud_new" AS ENUM ('EN_DESARROLLO', 'TESTING', 'LISTO_PARA_MERGE', 'MERGED', 'BORRADOR', 'COMPLETADA', 'CANCELADA');
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" DROP DEFAULT;
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" TYPE "EstadoSolicitud_new" USING ("ESTADO_SOL"::text::"EstadoSolicitud_new");
ALTER TYPE "EstadoSolicitud" RENAME TO "EstadoSolicitud_old";
ALTER TYPE "EstadoSolicitud_new" RENAME TO "EstadoSolicitud";
DROP TYPE "EstadoSolicitud_old";
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" SET DEFAULT 'BORRADOR';
COMMIT;

-- AlterTable
ALTER TABLE "SOLICITUDES_RAMAS" ADD COLUMN     "APPROVAL_DATE" TIMESTAMP,
ADD COLUMN     "REJECTION_COMMENT" TEXT,
ADD COLUMN     "REJECTION_DATE" TIMESTAMP;
