/*
  Warnings:

  - The values [NUEVA_FUNCIONALIDAD] on the enum `TipoCambio` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the `Carrera` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Curso` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Usuario` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterEnum
ALTER TYPE "EstadoSolicitud" ADD VALUE 'CERRADA';

-- AlterEnum
BEGIN;
CREATE TYPE "TipoCambio_new" AS ENUM ('FUNCIONALIDAD_NUEVA', 'MEJORA_EXISTENTE', 'CORRECCION_ERROR', 'CAMBIO_INTERFAZ', 'OPTIMIZACION', 'ACTUALIZACION_DATOS', 'OTRO');
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "TIPO_CAMBIO_SOL" TYPE "TipoCambio_new" USING ("TIPO_CAMBIO_SOL"::text::"TipoCambio_new");
ALTER TYPE "TipoCambio" RENAME TO "TipoCambio_old";
ALTER TYPE "TipoCambio_new" RENAME TO "TipoCambio";
DROP TYPE "TipoCambio_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "Cuenta" DROP CONSTRAINT "Cuenta_ID_USU_PER_fkey";

-- DropForeignKey
ALTER TABLE "Curso" DROP CONSTRAINT "Curso_CED_ORG_CUR_fkey";

-- DropForeignKey
ALTER TABLE "Curso" DROP CONSTRAINT "Curso_ID_CAT_CUR_fkey";

-- DropForeignKey
ALTER TABLE "EVENTOS_POR_CARRERA" DROP CONSTRAINT "EVENTOS_POR_CARRERA_ID_CAR_PER_fkey";

-- DropForeignKey
ALTER TABLE "Inscripcion" DROP CONSTRAINT "Inscripcion_ID_ADMIN_APROBADOR_fkey";

-- DropForeignKey
ALTER TABLE "Inscripcion" DROP CONSTRAINT "Inscripcion_ID_USU_INS_fkey";

-- DropForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" DROP CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey";

-- DropForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" DROP CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey";

-- DropForeignKey
ALTER TABLE "Usuario" DROP CONSTRAINT "Usuario_ID_CAR_PER_fkey";

-- DropTable
DROP TABLE "Carrera";

-- DropTable
DROP TABLE "Curso";

-- DropTable
DROP TABLE "Usuario";

-- CreateTable
CREATE TABLE "CARRERAS" (
    "ID_CAR" UUID NOT NULL,
    "NOM_CAR" VARCHAR(100) NOT NULL,
    "DES_CAR" VARCHAR(250) NOT NULL,
    "NOM_FAC_PER" VARCHAR(250) NOT NULL,

    CONSTRAINT "CARRERAS_pkey" PRIMARY KEY ("ID_CAR")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "ID_USU" UUID NOT NULL,
    "CED_USU" VARCHAR(20) NOT NULL,
    "NOM_USU1" VARCHAR(20) NOT NULL,
    "NOM_USU2" VARCHAR(20) NOT NULL,
    "APE_USU1" VARCHAR(20) NOT NULL,
    "APE_USU2" VARCHAR(20) NOT NULL,
    "FEC_NAC_USU" DATE NOT NULL,
    "NUM_TEL_USU" VARCHAR(10),
    "PAS_USU" VARCHAR(60),
    "ID_CAR_PER" UUID,
    "RESET_TOKEN" VARCHAR(255),
    "RESET_TOKEN_EXPIRY" TIMESTAMP(3),

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID_USU")
);

-- CreateTable
CREATE TABLE "CURSOS" (
    "ID_CUR" UUID NOT NULL,
    "NOM_CUR" VARCHAR(200) NOT NULL,
    "DES_CUR" VARCHAR(500) NOT NULL,
    "DUR_CUR" SMALLINT NOT NULL,
    "FEC_INI_CUR" DATE NOT NULL,
    "FEC_FIN_CUR" DATE NOT NULL,
    "ID_CAT_CUR" UUID NOT NULL,
    "CED_ORG_CUR" VARCHAR(10) NOT NULL,
    "CAPACIDAD_MAX_CUR" INTEGER NOT NULL,
    "TIPO_AUDIENCIA_CUR" "TipoAudienciaEvento" NOT NULL DEFAULT 'PUBLICO_GENERAL',

    CONSTRAINT "CURSOS_pkey" PRIMARY KEY ("ID_CUR")
);

-- CreateTable
CREATE TABLE "CURSOS_POR_CARRERA" (
    "ID_CUR_PER" UUID NOT NULL,
    "ID_CAR_PER" UUID NOT NULL,

    CONSTRAINT "CURSOS_POR_CARRERA_pkey" PRIMARY KEY ("ID_CUR_PER","ID_CAR_PER")
);

-- CreateTable
CREATE TABLE "ASIGNACIONES_CURSO" (
    "ID_ASI_CUR" UUID NOT NULL,
    "NOM_ASI_CUR" VARCHAR(100) NOT NULL,
    "DES_ASI_CUR" VARCHAR(250) NOT NULL,
    "ID_CUR_PER" UUID NOT NULL,

    CONSTRAINT "ASIGNACIONES_CURSO_pkey" PRIMARY KEY ("ID_ASI_CUR")
);

-- CreateTable
CREATE TABLE "REQUISITOS_CURSO" (
    "ID_REQ_CUR" UUID NOT NULL,
    "NOM_REQ_CUR" VARCHAR(100) NOT NULL,
    "DES_REQ_CUR" VARCHAR(250) NOT NULL,
    "ID_ASI_CUR_PER" UUID NOT NULL,

    CONSTRAINT "REQUISITOS_CURSO_pkey" PRIMARY KEY ("ID_REQ_CUR")
);

-- CreateTable
CREATE TABLE "INSCRIPCIONES_CURSO" (
    "ID_INS_CUR" UUID NOT NULL,
    "FEC_INS_CUR" DATE NOT NULL,
    "VAL_INS_CUR" DECIMAL(6,2) NOT NULL,
    "MET_PAG_INS_CUR" "MetodoPago" NOT NULL,
    "ENL_ORD_PAG_INS_CUR" TEXT,
    "ID_USU_INS_CUR" UUID NOT NULL,
    "ID_CUR_INS" UUID NOT NULL,
    "ESTADO_PAGO_CUR" "EstadoPago" NOT NULL DEFAULT 'PENDIENTE',
    "ID_ADMIN_APROBADOR_CUR" UUID,
    "FEC_APROBACION_CUR" DATE,

    CONSTRAINT "INSCRIPCIONES_CURSO_pkey" PRIMARY KEY ("ID_INS_CUR")
);

-- CreateTable
CREATE TABLE "PARTICIPACIONES_CURSO" (
    "ID_PAR_CUR" UUID NOT NULL,
    "NOT_PAR_CUR" DECIMAL(5,2) NOT NULL,
    "EST_PAR_CUR" "EstadoParticipacion" NOT NULL,
    "ASI_PAR_CUR" SMALLINT NOT NULL,
    "ID_INS_CUR_PER" UUID NOT NULL,
    "ENL_CER_PAR_CUR" TEXT,
    "FEC_CER_PAR_CUR" DATE,

    CONSTRAINT "PARTICIPACIONES_CURSO_pkey" PRIMARY KEY ("ID_PAR_CUR")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_CED_USU_key" ON "USUARIOS"("CED_USU");

-- CreateIndex
CREATE UNIQUE INDEX "INSCRIPCIONES_CURSO_ID_USU_INS_CUR_ID_CUR_INS_key" ON "INSCRIPCIONES_CURSO"("ID_USU_INS_CUR", "ID_CUR_INS");

-- CreateIndex
CREATE UNIQUE INDEX "PARTICIPACIONES_CURSO_ID_INS_CUR_PER_key" ON "PARTICIPACIONES_CURSO"("ID_INS_CUR_PER");

-- AddForeignKey
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cuenta" ADD CONSTRAINT "Cuenta_ID_USU_PER_fkey" FOREIGN KEY ("ID_USU_PER") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS_POR_CARRERA" ADD CONSTRAINT "EVENTOS_POR_CARRERA_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Inscripcion" ADD CONSTRAINT "Inscripcion_ID_USU_INS_fkey" FOREIGN KEY ("ID_USU_INS") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Inscripcion" ADD CONSTRAINT "Inscripcion_ID_ADMIN_APROBADOR_fkey" FOREIGN KEY ("ID_ADMIN_APROBADOR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey" FOREIGN KEY ("ID_USUARIO_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey" FOREIGN KEY ("ID_ADMIN_RESP_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS" ADD CONSTRAINT "CURSOS_ID_CAT_CUR_fkey" FOREIGN KEY ("ID_CAT_CUR") REFERENCES "CategoriaEvento"("ID_CAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS" ADD CONSTRAINT "CURSOS_CED_ORG_CUR_fkey" FOREIGN KEY ("CED_ORG_CUR") REFERENCES "Organizador"("CED_ORG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS_POR_CARRERA" ADD CONSTRAINT "CURSOS_POR_CARRERA_ID_CUR_PER_fkey" FOREIGN KEY ("ID_CUR_PER") REFERENCES "CURSOS"("ID_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS_POR_CARRERA" ADD CONSTRAINT "CURSOS_POR_CARRERA_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASIGNACIONES_CURSO" ADD CONSTRAINT "ASIGNACIONES_CURSO_ID_CUR_PER_fkey" FOREIGN KEY ("ID_CUR_PER") REFERENCES "CURSOS"("ID_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REQUISITOS_CURSO" ADD CONSTRAINT "REQUISITOS_CURSO_ID_ASI_CUR_PER_fkey" FOREIGN KEY ("ID_ASI_CUR_PER") REFERENCES "ASIGNACIONES_CURSO"("ID_ASI_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_USU_INS_CUR_fkey" FOREIGN KEY ("ID_USU_INS_CUR") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_CUR_INS_fkey" FOREIGN KEY ("ID_CUR_INS") REFERENCES "CURSOS"("ID_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_ADMIN_APROBADOR_CUR_fkey" FOREIGN KEY ("ID_ADMIN_APROBADOR_CUR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACIONES_CURSO" ADD CONSTRAINT "PARTICIPACIONES_CURSO_ID_INS_CUR_PER_fkey" FOREIGN KEY ("ID_INS_CUR_PER") REFERENCES "INSCRIPCIONES_CURSO"("ID_INS_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;
