/*
  Warnings:

  - The values [CANCELADO] on the enum `EstadoPago` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "TipoCambio" AS ENUM ('NUEVA_FUNCIONALIDAD', 'MEJORA_EXISTENTE', 'CORRECCION_ERROR', 'CAMBIO_INTERFAZ', 'OPTIMIZACION', 'ACTUALIZACION_DATOS', 'CAMBIO_SEGURIDAD', 'MIGRACION_DATOS', 'INTEGRACION_EXTERNA', 'OTRO');

-- CreateEnum
CREATE TYPE "PrioridadSolicitud" AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'CRITICA', 'URGENTE');

-- CreateEnum
CREATE TYPE "UrgenciaSolicitud" AS ENUM ('BAJA', 'NORMAL', 'ALTA', 'URGENTE', 'CRITICA');

-- CreateEnum
CREATE TYPE "RiesgoCambio" AS ENUM ('BAJO', 'MEDIO', 'ALTO', 'CRITICO');

-- CreateEnum
CREATE TYPE "CategoriaCambio" AS ENUM ('NORMAL', 'EXPEDITO', 'EMERGENCIA', 'ESTANDAR');

-- CreateEnum
CREATE TYPE "EstadoSolicitud" AS ENUM ('BORRADOR', 'PENDIENTE', 'EN_REVISION', 'PENDIENTE_APROBACION_TECNICA', 'PENDIENTE_APROBACION_NEGOCIO', 'APROBADA', 'RECHAZADA', 'CANCELADA', 'EN_DESARROLLO', 'PLANES_PENDIENTES_APROBACION', 'LISTO_PARA_IMPLEMENTAR', 'EN_TESTING', 'EN_DESPLIEGUE', 'COMPLETADA', 'FALLIDA', 'CERRADA', 'EN_PAUSA', 'ESPERANDO_INFORMACION');

-- AlterEnum
BEGIN;
CREATE TYPE "EstadoPago_new" AS ENUM ('PENDIENTE', 'APROBADO', 'RECHAZADO');
ALTER TABLE "INSCRIPCIONES" ALTER COLUMN "ESTADO_PAGO" DROP DEFAULT;
ALTER TABLE "INSCRIPCIONES_CURSO" ALTER COLUMN "ESTADO_PAGO_CUR" DROP DEFAULT;
ALTER TABLE "INSCRIPCIONES" ALTER COLUMN "ESTADO_PAGO" TYPE "EstadoPago_new" USING ("ESTADO_PAGO"::text::"EstadoPago_new");
ALTER TABLE "INSCRIPCIONES_CURSO" ALTER COLUMN "ESTADO_PAGO_CUR" TYPE "EstadoPago_new" USING ("ESTADO_PAGO_CUR"::text::"EstadoPago_new");
ALTER TYPE "EstadoPago" RENAME TO "EstadoPago_old";
ALTER TYPE "EstadoPago_new" RENAME TO "EstadoPago";
DROP TYPE "EstadoPago_old";
ALTER TABLE "INSCRIPCIONES" ALTER COLUMN "ESTADO_PAGO" SET DEFAULT 'PENDIENTE';
ALTER TABLE "INSCRIPCIONES_CURSO" ALTER COLUMN "ESTADO_PAGO_CUR" SET DEFAULT 'PENDIENTE';
COMMIT;

-- AlterEnum
ALTER TYPE "RolCuenta" ADD VALUE 'DESARROLLADOR';

-- CreateTable
CREATE TABLE "SOLICITUDES_CAMBIO" (
    "ID_SOL" UUID NOT NULL,
    "TITULO_SOL" VARCHAR(200) NOT NULL,
    "DESCRIPCION_SOL" TEXT NOT NULL,
    "JUSTIFICACION_SOL" TEXT NOT NULL,
    "TIPO_CAMBIO_SOL" "TipoCambio" NOT NULL,
    "PRIORIDAD_SOL" "PrioridadSolicitud" NOT NULL DEFAULT 'MEDIA',
    "URGENCIA_SOL" "UrgenciaSolicitud" NOT NULL DEFAULT 'NORMAL',
    "ESTADO_SOL" "EstadoSolicitud" NOT NULL DEFAULT 'BORRADOR',
    "IMPACTO_NEGOCIO_SOL" TEXT,
    "IMPACTO_TECNICO_SOL" TEXT,
    "RIESGO_CAMBIO_SOL" "RiesgoCambio" NOT NULL DEFAULT 'BAJO',
    "CATEGORIA_CAMBIO_SOL" "CategoriaCambio" NOT NULL DEFAULT 'NORMAL',
    "TIEMPO_INACTIVIDAD_ESTIMADO_SOL" VARCHAR(100),
    "USUARIOS_AFECTADOS_SOL" TEXT,
    "PLAN_IMPLEMENTACION_SOL" TEXT,
    "PLAN_ROLLOUT_SOL" TEXT,
    "PLAN_BACKOUT_SOL" TEXT,
    "PLAN_ROLLBACK_SOL" TEXT,
    "PLAN_TESTING_SOL" TEXT,
    "OBSERVACIONES_IMPLEMENTACION_SOL" TEXT,
    "PLANES_ENVIADOS_REVISION" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_ENVIO_PLANES" TIMESTAMP,
    "PLANES_APROBADOS" BOOLEAN DEFAULT false,
    "FECHA_APROBACION_PLANES" TIMESTAMP,
    "COMENTARIOS_APROBACION_PLANES" TEXT,
    "FECHA_PLANIFICADA_INICIO_SOL" DATE,
    "FECHA_PLANIFICADA_FIN_SOL" DATE,
    "HORA_PLANIFICADA_INICIO_SOL" VARCHAR(10),
    "HORA_PLANIFICADA_FIN_SOL" VARCHAR(10),
    "FECHA_REAL_INICIO_SOL" DATE,
    "FECHA_REAL_FIN_SOL" DATE,
    "HORA_REAL_INICIO_SOL" VARCHAR(10),
    "HORA_REAL_FIN_SOL" VARCHAR(10),
    "TIEMPO_ESTIMADO_HORAS_SOL" INTEGER,
    "TIEMPO_REAL_HORAS_SOL" INTEGER,
    "RECURSOS_NECESARIOS_SOL" TEXT,
    "BENEFICIOS_ESPERADOS_SOL" TEXT,
    "FECHA_LIMITE_DESEADA" DATE,
    "COMENTARIOS_ADMIN_SOL" TEXT,
    "COMENTARIOS_INTERNOS_SOL" TEXT,
    "COMENTARIOS_TECNICOS_SOL" TEXT,
    "EXITO_IMPLEMENTACION" BOOLEAN,
    "PROBLEMAS_ENCONTRADOS" TEXT,
    "SATISFACCION_USUARIO" SMALLINT,
    "GITHUB_REPO_URL" VARCHAR(500),
    "GITHUB_BRANCH_NAME" VARCHAR(200),
    "GITHUB_PR_NUMBER" INTEGER,
    "GITHUB_PR_URL" VARCHAR(500),
    "GITHUB_COMMITS" JSONB,
    "GITHUB_LAST_SYNC" TIMESTAMP,
    "FEC_CREACION_SOL" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_RESPUESTA_SOL" TIMESTAMP,
    "FEC_ULTIMA_ACTUALIZACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO_SOL" UUID NOT NULL,
    "ID_ADMIN_RESP_SOL" UUID,
    "ID_IMPLEMENTADOR" UUID,
    "ID_DESARROLLADOR_ASIGNADO" UUID,

    CONSTRAINT "SOLICITUDES_CAMBIO_pkey" PRIMARY KEY ("ID_SOL")
);

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey" FOREIGN KEY ("ID_USUARIO_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey" FOREIGN KEY ("ID_ADMIN_RESP_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_IMPLEMENTADOR_fkey" FOREIGN KEY ("ID_IMPLEMENTADOR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_DESARROLLADOR_ASIGNADO_fkey" FOREIGN KEY ("ID_DESARROLLADOR_ASIGNADO") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;
