-- AlterTable
ALTER TABLE "CURSOS" ADD COLUMN     "ES_GRATUITO" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "PRECIO" DECIMAL(6,2);

-- AlterTable
ALTER TABLE "EVENTOS" ADD COLUMN     "ES_GRATUITO" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "PRECIO" DECIMAL(6,2);

-- AlterTable
ALTER TABLE "INSCRIPCIONES" ALTER COLUMN "VAL_INS" DROP NOT NULL,
ALTER COLUMN "MET_PAG_INS" DROP NOT NULL;

-- AlterTable
ALTER TABLE "INSCRIPCIONES_CURSO" ALTER COLUMN "VAL_INS_CUR" DROP NOT NULL,
ALTER COLUMN "MET_PAG_INS_CUR" DROP NOT NULL;
