/*
  Warnings:

  - The values [PENDIENTE_APROBACION_TECNICA,PENDIENTE_APROBACION_NEGOCIO,CERRADA,EN_PAUSA,ESPERANDO_INFORMACION] on the enum `EstadoSolicitud` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `BENEFICIOS_ESPERADOS_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `FECHA_LIMITE_DESEADA` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `GITHUB_COMMITS` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `ID_IMPLEMENTADOR` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `OBSERVACIONES_IMPLEMENTACION_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `PLAN_ROLLBACK_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `PROBLEMAS_ENCONTRADOS` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `RECURSOS_NECESARIOS_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `SATISFACCION_USUARIO` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `TIEMPO_INACTIVIDAD_ESTIMADO_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.
  - You are about to drop the column `USUARIOS_AFECTADOS_SOL` on the `SOLICITUDES_CAMBIO` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "EstadoSolicitud_new" AS ENUM ('BORRADOR', 'PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'CANCELADA', 'EN_DESARROLLO', 'PLANES_PENDIENTES_APROBACION', 'LISTO_PARA_IMPLEMENTAR', 'ESPERANDO_APROBACION', 'EN_TESTING', 'EN_DESPLIEGUE', 'COMPLETADA', 'FALLIDA');
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" DROP DEFAULT;
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" TYPE "EstadoSolicitud_new" USING ("ESTADO_SOL"::text::"EstadoSolicitud_new");
ALTER TYPE "EstadoSolicitud" RENAME TO "EstadoSolicitud_old";
ALTER TYPE "EstadoSolicitud_new" RENAME TO "EstadoSolicitud";
DROP TYPE "EstadoSolicitud_old";
ALTER TABLE "SOLICITUDES_CAMBIO" ALTER COLUMN "ESTADO_SOL" SET DEFAULT 'BORRADOR';
COMMIT;

-- DropForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" DROP CONSTRAINT "SOLICITUDES_CAMBIO_ID_IMPLEMENTADOR_fkey";

-- AlterTable
ALTER TABLE "SOLICITUDES_CAMBIO" DROP COLUMN "BENEFICIOS_ESPERADOS_SOL",
DROP COLUMN "FECHA_LIMITE_DESEADA",
DROP COLUMN "GITHUB_COMMITS",
DROP COLUMN "ID_IMPLEMENTADOR",
DROP COLUMN "OBSERVACIONES_IMPLEMENTACION_SOL",
DROP COLUMN "PLAN_ROLLBACK_SOL",
DROP COLUMN "PROBLEMAS_ENCONTRADOS",
DROP COLUMN "RECURSOS_NECESARIOS_SOL",
DROP COLUMN "SATISFACCION_USUARIO",
DROP COLUMN "TIEMPO_INACTIVIDAD_ESTIMADO_SOL",
DROP COLUMN "USUARIOS_AFECTADOS_SOL",
ADD COLUMN     "COMENTARIOS_MASTER_PR_SOL" TEXT,
ADD COLUMN     "GITHUB_BASE_BRANCH" VARCHAR(100),
ADD COLUMN     "GITHUB_MERGED_AT" TIMESTAMP,
ADD COLUMN     "GITHUB_PR_STATE" VARCHAR(50),
ADD COLUMN     "GITHUB_REPOSITORY" VARCHAR(100),
ALTER COLUMN "GITHUB_REPO_URL" SET DATA TYPE TEXT,
ALTER COLUMN "GITHUB_BRANCH_NAME" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "GITHUB_PR_URL" SET DATA TYPE TEXT;

-- CreateIndex
CREATE INDEX "SOLICITUDES_CAMBIO_GITHUB_BRANCH_NAME_idx" ON "SOLICITUDES_CAMBIO"("GITHUB_BRANCH_NAME");

-- CreateIndex
CREATE INDEX "SOLICITUDES_CAMBIO_GITHUB_PR_NUMBER_idx" ON "SOLICITUDES_CAMBIO"("GITHUB_PR_NUMBER");

-- CreateIndex
CREATE INDEX "SOLICITUDES_CAMBIO_GITHUB_REPOSITORY_idx" ON "SOLICITUDES_CAMBIO"("GITHUB_REPOSITORY");
