-- CreateEnum
CREATE TYPE "TipoCambio" AS ENUM ('NUEVA_FUNCIONALIDAD', 'MEJORA_EXISTENTE', 'CORRECCION_ERROR', 'CAMBIO_INTERFAZ', 'OPTIMIZACION', 'OTRO');

-- CreateEnum
CREATE TYPE "PrioridadSolicitud" AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'CRITICA');

-- CreateEnum
CREATE TYPE "EstadoSolicitud" AS ENUM ('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'EN_DESARROLLO', 'COMPLETADA');

-- CreateTable
CREATE TABLE "SOLICITUDES_CAMBIO" (
    "ID_SOL" UUID NOT NULL,
    "TITULO_SOL" VARCHAR(200) NOT NULL,
    "DESCRIPCION_SOL" TEXT NOT NULL,
    "JUSTIFICACION_SOL" TEXT NOT NULL,
    "TIPO_CAMBIO_SOL" "TipoCambio" NOT NULL,
    "PRIORIDAD_SOL" "PrioridadSolicitud" NOT NULL DEFAULT 'MEDIA',
    "ESTADO_SOL" "EstadoSolicitud" NOT NULL DEFAULT 'PENDIENTE',
    "FEC_CREACION_SOL" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_RESPUESTA_SOL" TIMESTAMP,
    "COMENTARIOS_ADMIN_SOL" TEXT,
    "ID_USUARIO_SOL" UUID NOT NULL,
    "ID_ADMIN_RESP_SOL" UUID,

    CONSTRAINT "SOLICITUDES_CAMBIO_pkey" PRIMARY KEY ("ID_SOL")
);

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey" FOREIGN KEY ("ID_USUARIO_SOL") REFERENCES "Usuario"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey" FOREIGN KEY ("ID_ADMIN_RESP_SOL") REFERENCES "Usuario"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;
