-- =====================================================
-- MIGRACIÓN: Agregar campos faltantes a SOLICITUDES_CAMBIO
-- Fecha: Diciembre 2024
-- Descripción: Agregar todos los campos necesarios para la gestión técnica completa
-- =====================================================

-- Crear enums faltantes
CREATE TYPE "UrgenciaSolicitud" AS ENUM ('BAJA', 'NORMAL', 'ALTA', 'URGENTE', 'CRITICA');
CREATE TYPE "RiesgoCambio" AS ENUM ('BAJO', 'MEDIO', 'ALTO', 'CRITICO');
CREATE TYPE "CategoriaCambio" AS ENUM ('NORMAL', 'EXPEDITO', 'EMERGENCIA', 'ESTANDAR');

-- Actualizar enum de TipoCambio para incluir todos los valores
ALTER TYPE "TipoCambio" ADD VALUE 'ACTUALIZACION_DATOS';
ALTER TYPE "TipoCambio" ADD VALUE 'CAMBIO_SEGURIDAD';
ALTER TYPE "TipoCambio" ADD VALUE 'MIGRACION_DATOS';
ALTER TYPE "TipoCambio" ADD VALUE 'INTEGRACION_EXTERNA';

-- Actualizar enum de PrioridadSolicitud
ALTER TYPE "PrioridadSolicitud" ADD VALUE 'URGENTE';

-- Actualizar enum de EstadoSolicitud para incluir todos los estados
ALTER TYPE "EstadoSolicitud" ADD VALUE 'PENDIENTE_APROBACION_TECNICA';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'PENDIENTE_APROBACION_NEGOCIO';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'CANCELADA';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'EN_TESTING';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'EN_DESPLIEGUE';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'FALLIDA';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'CERRADA';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'EN_PAUSA';
ALTER TYPE "EstadoSolicitud" ADD VALUE 'ESPERANDO_INFORMACION';

-- Agregar campos básicos faltantes
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "URGENCIA_SOL" "UrgenciaSolicitud" DEFAULT 'NORMAL';

-- Agregar campos de análisis de impacto y riesgo
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "IMPACTO_NEGOCIO_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "IMPACTO_TECNICO_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "RIESGO_CAMBIO_SOL" "RiesgoCambio" DEFAULT 'BAJO';
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "CATEGORIA_CAMBIO_SOL" "CategoriaCambio" DEFAULT 'NORMAL';
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "TIEMPO_INACTIVIDAD_ESTIMADO_SOL" VARCHAR(100);
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "USUARIOS_AFECTADOS_SOL" TEXT;

-- Agregar campos de planes de implementación
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PLAN_IMPLEMENTACION_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PLAN_ROLLOUT_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PLAN_BACKOUT_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PLAN_ROLLBACK_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PLAN_TESTING_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "OBSERVACIONES_IMPLEMENTACION_SOL" TEXT;

-- Agregar campos de planificación temporal
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FECHA_PLANIFICADA_INICIO_SOL" DATE;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FECHA_PLANIFICADA_FIN_SOL" DATE;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "HORA_PLANIFICADA_INICIO_SOL" VARCHAR(10);
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "HORA_PLANIFICADA_FIN_SOL" VARCHAR(10);

ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FECHA_REAL_INICIO_SOL" DATE;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FECHA_REAL_FIN_SOL" DATE;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "HORA_REAL_INICIO_SOL" VARCHAR(10);
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "HORA_REAL_FIN_SOL" VARCHAR(10);

ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "TIEMPO_ESTIMADO_HORAS_SOL" INTEGER;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "TIEMPO_REAL_HORAS_SOL" INTEGER;

-- Agregar campos de recursos y comunicación
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "RECURSOS_NECESARIOS_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "BENEFICIOS_ESPERADOS_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FECHA_LIMITE_DESEADA" DATE;

-- Agregar campos de comentarios y seguimiento
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "COMENTARIOS_INTERNOS_SOL" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "COMENTARIOS_TECNICOS_SOL" TEXT;

-- Agregar campos de resultados y métricas
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "EXITO_IMPLEMENTACION" BOOLEAN;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "PROBLEMAS_ENCONTRADOS" TEXT;
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "SATISFACCION_USUARIO" SMALLINT;

-- Agregar campos de metadatos del sistema
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "FEC_ULTIMA_ACTUALIZACION" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar relación de implementador
ALTER TABLE "SOLICITUDES_CAMBIO" ADD COLUMN "ID_IMPLEMENTADOR" UUID;

-- Agregar foreign key para implementador
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_IMPLEMENTADOR_fkey" 
  FOREIGN KEY ("ID_IMPLEMENTADOR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- Actualizar foreign keys existentes para usar el nombre correcto de la tabla
ALTER TABLE "SOLICITUDES_CAMBIO" DROP CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey";
ALTER TABLE "SOLICITUDES_CAMBIO" DROP CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey";

ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey" 
  FOREIGN KEY ("ID_USUARIO_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey" 
  FOREIGN KEY ("ID_ADMIN_RESP_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- Crear índices para mejorar el rendimiento
CREATE INDEX "IDX_SOLICITUDES_ESTADO" ON "SOLICITUDES_CAMBIO"("ESTADO_SOL");
CREATE INDEX "IDX_SOLICITUDES_USUARIO" ON "SOLICITUDES_CAMBIO"("ID_USUARIO_SOL");
CREATE INDEX "IDX_SOLICITUDES_FECHA_CREACION" ON "SOLICITUDES_CAMBIO"("FEC_CREACION_SOL");
CREATE INDEX "IDX_SOLICITUDES_TIPO_CAMBIO" ON "SOLICITUDES_CAMBIO"("TIPO_CAMBIO_SOL");

-- Comentarios para documentación
COMMENT ON TABLE "SOLICITUDES_CAMBIO" IS 'Tabla principal para gestión de solicitudes de cambio';
COMMENT ON COLUMN "SOLICITUDES_CAMBIO"."RIESGO_CAMBIO_SOL" IS 'Evaluación del riesgo técnico del cambio';
COMMENT ON COLUMN "SOLICITUDES_CAMBIO"."CATEGORIA_CAMBIO_SOL" IS 'Categorización del tipo de proceso de cambio';
COMMENT ON COLUMN "SOLICITUDES_CAMBIO"."TIEMPO_INACTIVIDAD_ESTIMADO_SOL" IS 'Tiempo estimado de inactividad del sistema'; 