-- CreateEnum
CREATE TYPE "RolCuenta" AS ENUM ('ESTUDIANTE', 'USUARIO', 'MASTER', 'ADMINISTRADOR', 'DESARROLLADOR');

-- CreateEnum
CREATE TYPE "AreaEvento" AS ENUM ('PRACTICA', 'INVESTIGACION', 'ACADEMICA', 'TECNICA', 'INDUSTRIAL', 'EMPRESARIAL', 'IA', 'REDES');

-- CreateEnum
CREATE TYPE "TipoAudienciaEvento" AS ENUM ('CARRERA_ESPECIFICA', 'TODAS_CARRERAS', 'PUBLICO_GENERAL');

-- CreateEnum
CREATE TYPE "MetodoPago" AS ENUM ('TRANFERENCIA', 'DEPOSITO', 'TARJETA_CREDITO');

-- CreateEnum
CREATE TYPE "EstadoPago" AS ENUM ('PENDIENTE', 'APROBADO', 'RECHAZADO');

-- CreateEnum
CREATE TYPE "RepositoryType" AS ENUM ('FRONTEND', 'BACKEND');

-- CreateEnum
CREATE TYPE "PRStatus" AS ENUM ('PENDING', 'OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'MERGED');

-- CreateEnum
CREATE TYPE "TipoCambio" AS ENUM ('NUEVA_FUNCIONALIDAD', 'MEJORA_EXISTENTE', 'CORRECCION_ERROR', 'CAMBIO_INTERFAZ', 'OPTIMIZACION', 'ACTUALIZACION_DATOS', 'CAMBIO_SEGURIDAD', 'MIGRACION_DATOS', 'INTEGRACION_EXTERNA', 'OTRO');

-- CreateEnum
CREATE TYPE "PrioridadSolicitud" AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'CRITICA', 'URGENTE');

-- CreateEnum
CREATE TYPE "UrgenciaSolicitud" AS ENUM ('BAJA', 'NORMAL', 'ALTA', 'URGENTE', 'CRITICA');

-- CreateEnum
CREATE TYPE "RiesgoCambio" AS ENUM ('BAJO', 'MEDIO', 'ALTO', 'CRITICO');

-- CreateEnum
CREATE TYPE "CategoriaCambio" AS ENUM ('NORMAL', 'EXPEDITO', 'EMERGENCIA', 'ESTANDAR');

-- CreateEnum
CREATE TYPE "EstadoSolicitud" AS ENUM ('BORRADOR', 'PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'CANCELADA', 'EN_DESARROLLO', 'EN_TESTING', 'COMPLETADA', 'FALLIDA');

-- CreateEnum
CREATE TYPE "TipoReporte" AS ENUM ('FINANZAS', 'USUARIOS', 'CURSOS', 'EVENTOS', 'SOLICITUDES_ESTADO', 'SOLICITUDES_DESARROLLADOR', 'SOLICITUDES_RESUMEN');

-- CreateTable
CREATE TABLE "CARRERAS" (
    "ID_CAR" UUID NOT NULL,
    "NOM_CAR" VARCHAR(100) NOT NULL,
    "DES_CAR" VARCHAR(250) NOT NULL,
    "NOM_FAC_PER" VARCHAR(250) NOT NULL,

    CONSTRAINT "CARRERAS_pkey" PRIMARY KEY ("ID_CAR")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "ID_USU" UUID NOT NULL,
    "CED_USU" VARCHAR(20) NOT NULL,
    "NOM_USU1" VARCHAR(20) NOT NULL,
    "NOM_USU2" VARCHAR(20) NOT NULL,
    "APE_USU1" VARCHAR(20) NOT NULL,
    "APE_USU2" VARCHAR(20) NOT NULL,
    "FEC_NAC_USU" DATE NOT NULL,
    "NUM_TEL_USU" VARCHAR(10),
    "PAS_USU" VARCHAR(60),
    "ID_CAR_PER" UUID,
    "CEDULA_APROBADA" BOOLEAN NOT NULL DEFAULT false,
    "MATRICULA_APROBADA" BOOLEAN NOT NULL DEFAULT false,
    "ENL_CED_PDF" BYTEA,
    "ENL_MAT_PDF" BYTEA,
    "CEDULA_FILENAME" VARCHAR(255),
    "MATRICULA_FILENAME" VARCHAR(255),
    "CEDULA_SIZE" INTEGER,
    "MATRICULA_SIZE" INTEGER,
    "DOCUMENTOS_VERIFICADOS" BOOLEAN NOT NULL DEFAULT false,
    "FEC_VERIFICACION_DOCS" TIMESTAMP,
    "RESET_TOKEN" VARCHAR(255),
    "RESET_TOKEN_EXPIRY" TIMESTAMP(3),
    "GITHUB_TOKEN" VARCHAR(255),
    "GITHUB_USERNAME" VARCHAR(100),

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID_USU")
);

-- CreateTable
CREATE TABLE "CUENTAS" (
    "ID_CUE" UUID NOT NULL,
    "COR_CUE" VARCHAR(150) NOT NULL,
    "ROL_CUE" "RolCuenta" NOT NULL,
    "ID_USU_PER" UUID NOT NULL,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "emailVerificationToken" TEXT,
    "emailVerificationExpiry" TIMESTAMP(3),

    CONSTRAINT "CUENTAS_pkey" PRIMARY KEY ("ID_CUE")
);

-- CreateTable
CREATE TABLE "ORGANIZADORES" (
    "CED_ORG" VARCHAR(10) NOT NULL,
    "NOM_ORG1" VARCHAR(20) NOT NULL,
    "NOM_ORG2" VARCHAR(20) NOT NULL,
    "APE_ORG1" VARCHAR(20) NOT NULL,
    "APE_ORG2" VARCHAR(20) NOT NULL,
    "TIT_ACA_ORG" VARCHAR(100),

    CONSTRAINT "ORGANIZADORES_pkey" PRIMARY KEY ("CED_ORG")
);

-- CreateTable
CREATE TABLE "CATEGORIAS_EVENTO" (
    "ID_CAT" UUID NOT NULL,
    "NOM_CAT" VARCHAR(50) NOT NULL,
    "DES_CAT" VARCHAR(250) NOT NULL,

    CONSTRAINT "CATEGORIAS_EVENTO_pkey" PRIMARY KEY ("ID_CAT")
);

-- CreateTable
CREATE TABLE "EVENTOS" (
    "ID_EVE" UUID NOT NULL,
    "NOM_EVE" VARCHAR(250) NOT NULL,
    "DES_EVE" VARCHAR(500) NOT NULL,
    "ID_CAT_EVE" UUID NOT NULL,
    "FEC_INI_EVE" DATE NOT NULL,
    "FEC_FIN_EVE" DATE,
    "HOR_INI_EVE" TIME NOT NULL,
    "HOR_FIN_EVE" TIME,
    "DUR_EVE" SMALLINT NOT NULL,
    "ARE_EVE" "AreaEvento" NOT NULL,
    "UBI_EVE" VARCHAR(150) NOT NULL,
    "CED_ORG_EVE" VARCHAR(10) NOT NULL,
    "CAPACIDAD_MAX_EVE" INTEGER NOT NULL,
    "TIPO_AUDIENCIA_EVE" "TipoAudienciaEvento" NOT NULL DEFAULT 'PUBLICO_GENERAL',
    "ES_GRATUITO" BOOLEAN NOT NULL DEFAULT true,
    "PRECIO" DECIMAL(6,2),
    "PORCENTAJE_ASISTENCIA_APROBACION" SMALLINT NOT NULL DEFAULT 80,
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    "REQUIERE_CARTA_MOTIVACION" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "EVENTOS_pkey" PRIMARY KEY ("ID_EVE")
);

-- CreateTable
CREATE TABLE "EVENTOS_POR_CARRERA" (
    "ID_EVE_PER" UUID NOT NULL,
    "ID_CAR_PER" UUID NOT NULL,

    CONSTRAINT "EVENTOS_POR_CARRERA_pkey" PRIMARY KEY ("ID_EVE_PER","ID_CAR_PER")
);

-- CreateTable
CREATE TABLE "INSCRIPCIONES" (
    "ID_INS" UUID NOT NULL,
    "FEC_INS" DATE NOT NULL,
    "VAL_INS" DECIMAL(6,2),
    "MET_PAG_INS" "MetodoPago",
    "ENL_ORD_PAG_INS" TEXT,
    "COMPROBANTE_PAGO_PDF" BYTEA,
    "COMPROBANTE_FILENAME" VARCHAR(255),
    "COMPROBANTE_SIZE" INTEGER,
    "FEC_SUBIDA_COMPROBANTE" TIMESTAMP,
    "ID_USU_INS" UUID NOT NULL,
    "ID_EVE_INS" UUID NOT NULL,
    "ESTADO_PAGO" "EstadoPago" NOT NULL DEFAULT 'PENDIENTE',
    "ID_ADMIN_APROBADOR" UUID,
    "FEC_APROBACION" DATE,
    "CARTA_MOTIVACION" VARCHAR(500),

    CONSTRAINT "INSCRIPCIONES_pkey" PRIMARY KEY ("ID_INS")
);

-- CreateTable
CREATE TABLE "PARTICIPACIONES" (
    "ID_PAR" UUID NOT NULL,
    "ASI_PAR" SMALLINT NOT NULL,
    "APROBADO" BOOLEAN NOT NULL DEFAULT false,
    "CERTIFICADO_PDF" BYTEA,
    "CERTIFICADO_FILENAME" VARCHAR(255),
    "CERTIFICADO_SIZE" INTEGER,
    "FEC_CER_PAR" DATE,
    "FEC_EVALUACION" TIMESTAMP,
    "ID_INS_PER" UUID NOT NULL,

    CONSTRAINT "PARTICIPACIONES_pkey" PRIMARY KEY ("ID_PAR")
);

-- CreateTable
CREATE TABLE "CURSOS" (
    "ID_CUR" UUID NOT NULL,
    "NOM_CUR" VARCHAR(200) NOT NULL,
    "DES_CUR" VARCHAR(500) NOT NULL,
    "DUR_CUR" SMALLINT NOT NULL,
    "FEC_INI_CUR" DATE NOT NULL,
    "FEC_FIN_CUR" DATE NOT NULL,
    "ID_CAT_CUR" UUID NOT NULL,
    "CED_ORG_CUR" VARCHAR(10) NOT NULL,
    "CAPACIDAD_MAX_CUR" INTEGER NOT NULL,
    "TIPO_AUDIENCIA_CUR" "TipoAudienciaEvento" NOT NULL DEFAULT 'PUBLICO_GENERAL',
    "REQUIERE_VERIFICACION_DOCS" BOOLEAN NOT NULL DEFAULT true,
    "ES_GRATUITO" BOOLEAN NOT NULL DEFAULT true,
    "PRECIO" DECIMAL(6,2),
    "REQUIERE_CARTA_MOTIVACION" BOOLEAN NOT NULL DEFAULT false,
    "PORCENTAJE_ASISTENCIA_APROBACION" SMALLINT NOT NULL DEFAULT 80,
    "NOTA_MINIMA_APROBACION" DECIMAL(3,1) NOT NULL DEFAULT 7.0,
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

    CONSTRAINT "CURSOS_pkey" PRIMARY KEY ("ID_CUR")
);

-- CreateTable
CREATE TABLE "CURSOS_POR_CARRERA" (
    "ID_CUR_PER" UUID NOT NULL,
    "ID_CAR_PER" UUID NOT NULL,

    CONSTRAINT "CURSOS_POR_CARRERA_pkey" PRIMARY KEY ("ID_CUR_PER","ID_CAR_PER")
);

-- CreateTable
CREATE TABLE "INSCRIPCIONES_CURSO" (
    "ID_INS_CUR" UUID NOT NULL,
    "FEC_INS_CUR" DATE NOT NULL,
    "VAL_INS_CUR" DECIMAL(6,2),
    "MET_PAG_INS_CUR" "MetodoPago",
    "ENL_ORD_PAG_INS_CUR" TEXT,
    "COMPROBANTE_PAGO_PDF" BYTEA,
    "COMPROBANTE_FILENAME" VARCHAR(255),
    "COMPROBANTE_SIZE" INTEGER,
    "FEC_SUBIDA_COMPROBANTE" TIMESTAMP,
    "ID_USU_INS_CUR" UUID NOT NULL,
    "ID_CUR_INS" UUID NOT NULL,
    "CARTA_MOTIVACION" VARCHAR(500),
    "ESTADO_PAGO_CUR" "EstadoPago" NOT NULL DEFAULT 'PENDIENTE',
    "ID_ADMIN_APROBADOR_CUR" UUID,
    "FEC_APROBACION_CUR" DATE,

    CONSTRAINT "INSCRIPCIONES_CURSO_pkey" PRIMARY KEY ("ID_INS_CUR")
);

-- CreateTable
CREATE TABLE "PARTICIPACIONES_CURSO" (
    "ID_PAR_CUR" UUID NOT NULL,
    "NOTA_FINAL" DECIMAL(5,2) NOT NULL,
    "ASISTENCIA_PORCENTAJE" DECIMAL(5,2) NOT NULL,
    "APROBADO" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_EVALUACION" TIMESTAMP,
    "CERTIFICADO_PDF" BYTEA,
    "CERTIFICADO_FILENAME" VARCHAR(255),
    "CERTIFICADO_SIZE" INTEGER,
    "FEC_CER_PAR_CUR" DATE,
    "ID_INS_CUR_PER" UUID NOT NULL,

    CONSTRAINT "PARTICIPACIONES_CURSO_pkey" PRIMARY KEY ("ID_PAR_CUR")
);

-- CreateTable
CREATE TABLE "SOLICITUDES_CAMBIO" (
    "ID_SOL" UUID NOT NULL,
    "TITULO_SOL" VARCHAR(200) NOT NULL,
    "DESCRIPCION_SOL" TEXT NOT NULL,
    "JUSTIFICACION_SOL" TEXT NOT NULL,
    "TIPO_CAMBIO_SOL" "TipoCambio" NOT NULL,
    "PRIORIDAD_SOL" "PrioridadSolicitud" NOT NULL DEFAULT 'MEDIA',
    "URGENCIA_SOL" "UrgenciaSolicitud" NOT NULL DEFAULT 'NORMAL',
    "ESTADO_SOL" "EstadoSolicitud" NOT NULL DEFAULT 'BORRADOR',
    "IMPACTO_NEGOCIO_SOL" TEXT,
    "IMPACTO_TECNICO_SOL" TEXT,
    "RIESGO_CAMBIO_SOL" "RiesgoCambio" NOT NULL DEFAULT 'BAJO',
    "CATEGORIA_CAMBIO_SOL" "CategoriaCambio" NOT NULL DEFAULT 'NORMAL',
    "PLAN_IMPLEMENTACION_SOL" TEXT,
    "PLAN_ROLLOUT_SOL" TEXT,
    "PLAN_BACKOUT_SOL" TEXT,
    "PLAN_TESTING_SOL" TEXT,
    "PLANES_ENVIADOS_REVISION" BOOLEAN NOT NULL DEFAULT false,
    "FECHA_ENVIO_PLANES" TIMESTAMP,
    "PLANES_APROBADOS" BOOLEAN DEFAULT false,
    "FECHA_APROBACION_PLANES" TIMESTAMP,
    "COMENTARIOS_APROBACION_PLANES" TEXT,
    "FECHA_PLANIFICADA_INICIO_SOL" DATE,
    "FECHA_PLANIFICADA_FIN_SOL" DATE,
    "HORA_PLANIFICADA_INICIO_SOL" VARCHAR(10),
    "HORA_PLANIFICADA_FIN_SOL" VARCHAR(10),
    "TIEMPO_ESTIMADO_HORAS_SOL" INTEGER,
    "FECHA_REAL_INICIO_SOL" DATE,
    "FECHA_REAL_FIN_SOL" DATE,
    "HORA_REAL_INICIO_SOL" VARCHAR(10),
    "HORA_REAL_FIN_SOL" VARCHAR(10),
    "TIEMPO_REAL_HORAS_SOL" INTEGER,
    "COMENTARIOS_ADMIN_SOL" TEXT,
    "COMENTARIOS_INTERNOS_SOL" TEXT,
    "COMENTARIOS_TECNICOS_SOL" TEXT,
    "EXITO_IMPLEMENTACION" BOOLEAN,
    "GITHUB_REPO_URL" VARCHAR(500),
    "FEC_CREACION_SOL" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FEC_RESPUESTA_SOL" TIMESTAMP,
    "FEC_ULTIMA_ACTUALIZACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO_SOL" UUID NOT NULL,
    "ID_ADMIN_RESP_SOL" UUID,
    "ID_DESARROLLADOR_ASIGNADO" UUID,

    CONSTRAINT "SOLICITUDES_CAMBIO_pkey" PRIMARY KEY ("ID_SOL")
);

-- CreateTable
CREATE TABLE "SOLICITUDES_RAMAS" (
    "ID" UUID NOT NULL,
    "ID_SOLICITUD" UUID NOT NULL,
    "REPOSITORY_TYPE" "RepositoryType" NOT NULL,
    "BRANCH_NAME" VARCHAR(255) NOT NULL,
    "PR_NUMBER" INTEGER,
    "PR_URL" VARCHAR(500),
    "PR_STATE" VARCHAR(50),
    "PR_STATUS" "PRStatus" NOT NULL DEFAULT 'PENDING',
    "COMENTARIOS_APROBACION" TEXT,
    "FECHA_APROBACION" TIMESTAMP,
    "COMENTARIOS_RECHAZO" TEXT,
    "FECHA_RECHAZO" TIMESTAMP,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MERGED_AT" TIMESTAMP,
    "FECHA_MERGE" TIMESTAMP,
    "LAST_SYNC" TIMESTAMP,

    CONSTRAINT "SOLICITUDES_RAMAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PAGINA_PRINCIPAL" (
    "ID_PAG" UUID NOT NULL,
    "TITULO_HERO" VARCHAR(200),
    "SUBTITULO_HERO" VARCHAR(300),
    "DESCRIPCION_HERO" VARCHAR(500),
    "IMAGEN_HERO" BYTEA,
    "TITULO_OFRECEMOS" VARCHAR(100),
    "SUBTITULO_OFRECEMOS" VARCHAR(300),
    "TITULO_SECCION1" VARCHAR(100),
    "DESCRIPCION_SECCION1" TEXT,
    "IMAGEN_SECCION1" BYTEA,
    "TITULO_SECCION2" VARCHAR(100),
    "DESCRIPCION_SECCION2" TEXT,
    "IMAGEN_SECCION2" BYTEA,
    "TITULO_SECCION3" VARCHAR(100),
    "DESCRIPCION_SECCION3" TEXT,
    "IMAGEN_SECCION3" BYTEA,
    "TITULO_SECCION4" VARCHAR(100),
    "DESCRIPCION_SECCION4" TEXT,
    "IMAGEN_SECCION4" BYTEA,
    "TEXTO_FOOTER1" VARCHAR(200),
    "TEXTO_FOOTER2" VARCHAR(200),
    "TEXTO_FOOTER3" VARCHAR(200),
    "FECHA_CREACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_ULTIMA_ACTUALIZACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO_ULTIMA_EDICION" UUID,
    "DES_PAG" VARCHAR(1000),
    "MIS_PAG" VARCHAR(1000),
    "VIS_PAG" VARCHAR(1000),

    CONSTRAINT "PAGINA_PRINCIPAL_pkey" PRIMARY KEY ("ID_PAG")
);

-- CreateTable
CREATE TABLE "REPORTES" (
    "ID_REP" UUID NOT NULL,
    "TIPO" "TipoReporte" NOT NULL,
    "NOMBRE_ARCHIVO" VARCHAR(255) NOT NULL,
    "ARCHIVO_PDF" BYTEA NOT NULL,
    "FECHA_GENERADO" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "REPORTES_pkey" PRIMARY KEY ("ID_REP")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_CED_USU_key" ON "USUARIOS"("CED_USU");

-- CreateIndex
CREATE UNIQUE INDEX "INSCRIPCIONES_ID_USU_INS_ID_EVE_INS_key" ON "INSCRIPCIONES"("ID_USU_INS", "ID_EVE_INS");

-- CreateIndex
CREATE UNIQUE INDEX "PARTICIPACIONES_ID_INS_PER_key" ON "PARTICIPACIONES"("ID_INS_PER");

-- CreateIndex
CREATE UNIQUE INDEX "INSCRIPCIONES_CURSO_ID_USU_INS_CUR_ID_CUR_INS_key" ON "INSCRIPCIONES_CURSO"("ID_USU_INS_CUR", "ID_CUR_INS");

-- CreateIndex
CREATE UNIQUE INDEX "PARTICIPACIONES_CURSO_ID_INS_CUR_PER_key" ON "PARTICIPACIONES_CURSO"("ID_INS_CUR_PER");

-- CreateIndex
CREATE UNIQUE INDEX "SOLICITUDES_RAMAS_ID_SOLICITUD_REPOSITORY_TYPE_key" ON "SOLICITUDES_RAMAS"("ID_SOLICITUD", "REPOSITORY_TYPE");

-- AddForeignKey
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUENTAS" ADD CONSTRAINT "CUENTAS_ID_USU_PER_fkey" FOREIGN KEY ("ID_USU_PER") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS" ADD CONSTRAINT "EVENTOS_ID_CAT_EVE_fkey" FOREIGN KEY ("ID_CAT_EVE") REFERENCES "CATEGORIAS_EVENTO"("ID_CAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS" ADD CONSTRAINT "EVENTOS_CED_ORG_EVE_fkey" FOREIGN KEY ("CED_ORG_EVE") REFERENCES "ORGANIZADORES"("CED_ORG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS_POR_CARRERA" ADD CONSTRAINT "EVENTOS_POR_CARRERA_ID_EVE_PER_fkey" FOREIGN KEY ("ID_EVE_PER") REFERENCES "EVENTOS"("ID_EVE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS_POR_CARRERA" ADD CONSTRAINT "EVENTOS_POR_CARRERA_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_ID_USU_INS_fkey" FOREIGN KEY ("ID_USU_INS") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_ID_EVE_INS_fkey" FOREIGN KEY ("ID_EVE_INS") REFERENCES "EVENTOS"("ID_EVE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES" ADD CONSTRAINT "INSCRIPCIONES_ID_ADMIN_APROBADOR_fkey" FOREIGN KEY ("ID_ADMIN_APROBADOR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACIONES" ADD CONSTRAINT "PARTICIPACIONES_ID_INS_PER_fkey" FOREIGN KEY ("ID_INS_PER") REFERENCES "INSCRIPCIONES"("ID_INS") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS" ADD CONSTRAINT "CURSOS_ID_CAT_CUR_fkey" FOREIGN KEY ("ID_CAT_CUR") REFERENCES "CATEGORIAS_EVENTO"("ID_CAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS" ADD CONSTRAINT "CURSOS_CED_ORG_CUR_fkey" FOREIGN KEY ("CED_ORG_CUR") REFERENCES "ORGANIZADORES"("CED_ORG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS_POR_CARRERA" ADD CONSTRAINT "CURSOS_POR_CARRERA_ID_CUR_PER_fkey" FOREIGN KEY ("ID_CUR_PER") REFERENCES "CURSOS"("ID_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CURSOS_POR_CARRERA" ADD CONSTRAINT "CURSOS_POR_CARRERA_ID_CAR_PER_fkey" FOREIGN KEY ("ID_CAR_PER") REFERENCES "CARRERAS"("ID_CAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_USU_INS_CUR_fkey" FOREIGN KEY ("ID_USU_INS_CUR") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_CUR_INS_fkey" FOREIGN KEY ("ID_CUR_INS") REFERENCES "CURSOS"("ID_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INSCRIPCIONES_CURSO" ADD CONSTRAINT "INSCRIPCIONES_CURSO_ID_ADMIN_APROBADOR_CUR_fkey" FOREIGN KEY ("ID_ADMIN_APROBADOR_CUR") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACIONES_CURSO" ADD CONSTRAINT "PARTICIPACIONES_CURSO_ID_INS_CUR_PER_fkey" FOREIGN KEY ("ID_INS_CUR_PER") REFERENCES "INSCRIPCIONES_CURSO"("ID_INS_CUR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_USUARIO_SOL_fkey" FOREIGN KEY ("ID_USUARIO_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_ADMIN_RESP_SOL_fkey" FOREIGN KEY ("ID_ADMIN_RESP_SOL") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_CAMBIO" ADD CONSTRAINT "SOLICITUDES_CAMBIO_ID_DESARROLLADOR_ASIGNADO_fkey" FOREIGN KEY ("ID_DESARROLLADOR_ASIGNADO") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUDES_RAMAS" ADD CONSTRAINT "SOLICITUDES_RAMAS_ID_SOLICITUD_fkey" FOREIGN KEY ("ID_SOLICITUD") REFERENCES "SOLICITUDES_CAMBIO"("ID_SOL") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PAGINA_PRINCIPAL" ADD CONSTRAINT "PAGINA_PRINCIPAL_ID_USUARIO_ULTIMA_EDICION_fkey" FOREIGN KEY ("ID_USUARIO_ULTIMA_EDICION") REFERENCES "USUARIOS"("ID_USU") ON DELETE SET NULL ON UPDATE CASCADE;
